# Generated by Django 3.1 on 2021-02-06 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(max_length=254)),
                ('order_date', models.DateTimeField()),
                ('order_size', models.PositiveSmallIntegerField(default=1)),
                ('unique_auth', models.CharField(max_length=256)),
                ('expiry_date', models.DateTimeField()),
                ('has_confirmed', models.BooleanField(default=False)),
                ('charity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.charityaccount')),
            ],
        ),
    ]
